### PR TITLE
Disable Chrome sandbox when unavailable

### PR DESCRIPTION
**Pull request by filipesilva**
Chrome on Linux uses sandboxing, which needs user namespaces to be enabled.
This is not available on all kernels and it might be turned off even if it is available.
Notable examples where user namespaces are not available include:

- In Debian it is compiled-in but disabled by default.
- The Docker daemon for Windows or OSX does not support user namespaces.

We can detect if user namespaces are supported via /proc/sys/kernel/unprivileged_userns_clone.

For more information see:
https://github.com/Googlechrome/puppeteer/issues/290
https://superuser.com/questions/1094597/enable-user-namespaces-in-debian-kernel#1122977
https://github.com/karma-runner/karma-chrome-launcher/issues/158
https://github.com/angular/angular/pull/24906

### CODE REVIEW

**Comment by alexeagle** [comment]
@huangw5 I think you also ran into chrome sandboxing vs. running as root - any idea if this is the right thing to do?

**Comment by filipesilva** [comment]
In https://github.com/angular/angular/pull/24906 there is also a check to see if the current user is root. It could be added here.

**Comment by filipesilva** [comment]
I think the problem I am trying to solve here is different because running chrome in docker on a linux host already works, but doesn't support namespaces on windows and osx hosts (breaking chrome sandboxes).

@huangw5 if I understand this correctly, running docker with `--cap-add SYS_ADMIN` means "add admin capabilities" (as per https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities). I think that makes sense if the docker user is already root but it probably shouldn't be on when using a non-root user.

**Comment by filipesilva** [comment]
Broken CI seems related to https://github.com/bazelbuild/rules_typescript/pull/312

**Pull request merged**
