### PR TITLE
Add ability to run tslint under bazel

### PR DESCRIPTION
**Pull request by alexeagle**
see #10

### CODE REVIEW

**Comment by alexeagle** [comment]
Demo, running on this repo. The path reporting should be relativized to `rootDir` obviously...

```
$ bazel build ... --config=lint
INFO: Found 27 targets...
ERROR: /Users/alexeagle/Projects/rules_typescript/tslint/BUILD.bazel:18:1: Executing extra_action @build_bazel_rules_typescript//tslint:tslint_action on //tslint:tslint_runner failed (Exit 1).

ERROR: /private/var/tmp/_bazel_alexeagle/9261c0c5eb4bc2bbfc16e8ad582ca52f/bazel-sandbox/8857059394672278361/execroot/build_bazel_rules_typescript/tslint/tslint_runner.ts[19, 7]: Identifier 'protoPath' is never reassigned; use 'const' instead of 'let'.
ERROR: /private/var/tmp/_bazel_alexeagle/9261c0c5eb4bc2bbfc16e8ad582ca52f/bazel-sandbox/8857059394672278361/execroot/build_bazel_rules_typescript/tslint/tslint_runner.ts[13, 7]: variable name must be in lowerCamelCase or UPPER_CASE
ERROR: /private/var/tmp/_bazel_alexeagle/9261c0c5eb4bc2bbfc16e8ad582ca52f/bazel-sandbox/8857059394672278361/execroot/build_bazel_rules_typescript/tslint/tslint_runner.ts[13, 7]: 'ByteBuffer' is declared but never used.
ERROR: /private/var/tmp/_bazel_alexeagle/9261c0c5eb4bc2bbfc16e8ad582ca52f/bazel-sandbox/8857059394672278361/execroot/build_bazel_rules_typescript/tslint/tslint_runner.ts[7, 33]: 'IOptions' is declared but never used.
```

**Comment by mgechev** [comment]
Can we close this or we can rebase it and push it to master?

**Comment by alexeagle** [comment]
Still might be something we want to do eventually, just leaving it open for now

**Comment by alexeagle** [comment]
tslint is dead, closing

**Pull request closed without merging**
