### PR TITLE
Ignore declarationDir compiler option

### LINKED ISSUE #32: Actual location of generated d.ts file outputs do not match expected with declarationDir
As per discussion in #30.  Bazel expects the generated d.ts files to be siblings of the generated js files.  The tsc/tsconfig declarationDir option throws this off, causing the ts_library rule to fail.

### PR DESCRIPTION
**Pull request by pcj**
Fixes #32

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by alexeagle** [comment]
How does this solution compare with just overriding the `declarationDir` in tsconfig.bzl like we do for other options like `outDir`? I'd rather treat them all the same way.

**Comment by pcj** [comment]
Apologies for delay, thanks for pointing out `tsconfig.bzl`.  I force pushed a different commit.  

It fixes the issue for `ts-protoc-gen`.  In this scenario, we're always emitting a value for `declarationDir` in the generated `tsconfig.json` file, which implies that these tsconfig files will be incompatible with older versions of tsc (built before https://github.com/Microsoft/TypeScript/pull/7170, March 24, 2016).  Let me know if you think this will be an issue.

**Comment by alexeagle** [comment]
Thanks!
Yes, we already specify a dependency on TS 2.4 (the tsc-wrapped compiler is tightly coupled with the version of TypeScript)

**Pull request closed without merging**
