### PR TITLE
Tsetse perf

### PR DESCRIPTION
**Pull request by clydin**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [X] Refactoring (no functional changes, no api changes)

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

Several small performance related refactoring changes for the tsetse rules.

## Does this PR introduce a breaking change?
- [X] No

## Other information

//cc @filipesilva

### CODE REVIEW

**Comment by filipesilva** [comment]
The Windows CI is failing but it doesn't really seem related to these code changes:
```

ERROR: D:/b/jpdvqxn5/external/io_bazel_rules_webtesting/third_party/chromium/BUILD.bazel:25:1: Couldn't build file external/io_bazel_rules_webtesting/third_party/chromium/chromium.out: Extracting ../org_chromium_chromium/file/chrome-win32.zip failed (Exit 1): extract.bat failed: error executing command
--
  | cd D:/b/jpdvqxn5/execroot/build_bazel_rules_typescript
  | SET PATH=C:\tools\msys64\usr\bin;C:\tools\msys64\bin
  | external/io_bazel_rules_webtesting/web/internal/extract.bat external/org_chromium_chromium/file/chrome-win32.zip bazel-out/x64_windows-fastbuild/bin/external/io_bazel_rules_webtesting/third_party/chromium/chromium.out
  | Execution platform: @bazel_tools//platforms:host_platform
  | 'powershell.exe' is not recognized as an internal or external command,
  | operable program or batch file.

```

If anything, it seems related to https://github.com/bazelbuild/rules_typescript/pull/356. @meteorcloudy do you know what is going on?

**Comment by meteorcloudy** [comment]
Looks like we still need to add `--action_env=PATH` in the Bazel config file. Filed https://github.com/bazelbuild/rules_typescript/pull/373

**Comment by alexeagle** [comment]
@clydin just found this one again - please escalate if you have PRs that are stuck and not getting merged!

**Comment by alexeagle** [comment]
tssync to cl/231970240

**Pull request closed without merging**
