### PR TITLE
Search in @types directory for modules too.

### LINKED ISSUE #179: Type resolution fails with bazel managed npm_modules
I have the following build rule:

~~~
ts_library(
    name = "client",
    srcs = glob(["control.ts", "xray_viewer.ts"]),
    tsconfig = "//:tsconfig.json",
    node_modules = "@third_party_js//:node_modules", # or "//:node_modules".
)
~~~

If I manage my `node_modules` myself and check it into my repo root, this build rule works. I want to move to bazel managed dependencies though, so I added 

~~~
yarn_install(
    name = "third_party_js",
    package_json = "//:package.json",
    yarn_lock = "//:yarn.lock",
)
~~~

for managing my javascript dependencies and depend on the new `@third_party_js//:node_modules` rule. This now no longer compiles:

~~~
third_party/point_cloud_viewer/xray/client/control.ts(17,24): error TS7016: Could not find a declaration file for module 'three'. '/home/hrapp/.cache/ba
zel/_bazel_hrapp/8de0a1069de8d166c668173ca21c04ae/bazel-sandbox/7039943917462986036/execroot/com_lyft_avsoftware/external/third_party_js/node_modules/th
ree/build/three.js' implicitly has an 'any' type.
~~~

I investigated a bit. The problem in the generated [`tsconfig.file` (Gist)](https://gist.github.com/2f5d91d34eef300be1eda7f276fae609) is in the [`path` setting](https://gist.github.com/SirVer/2f5d91d34eef300be1eda7f276fae609#file-client_es5_tsconfig-json-L40) and in the [`typeRoots` setting](https://gist.github.com/SirVer/2f5d91d34eef300be1eda7f276fae609#file-client_es5_tsconfig-json-L61).

According to https://github.com/Microsoft/TypeScript/issues/13581#issuecomment-274291670, `typeRoots` is not used for type resolution for modules, i.e. `three` in this case. It is searched when a `node_modules` is found in a top level directory for the files that are compiled, that is why it is found if node_modules is checked into my repository.

A possible and easy fix is to add `node_modules/@types` to `paths` - so that the type definitions are found. I proposed a fix for this in a separate PR.

### PR DESCRIPTION
**Pull request by SirVer**
Fixes #179.

### CODE REVIEW

**Comment by SirVer** [comment]
@alexeagle Thanks for the documentation change. It makes the intent much clearer! Can this be merged?

**Comment by SirVer** [comment]
@alexeagle friendly ping?

**Comment by SirVer** [comment]
@alexeagle Alex, we here at Lyft like to see this merged. What can I do to expedite this?

**Comment by alexeagle** [comment]
Gah, thank you for pinging this again. I'm sorry, last week was ng-conf and I was very heads-down getting Angular moved to these rules and doing a workshop.

This one is missing some testing, which I've just added. It also has to go through internal review and land in our internal repo first before the merge can sync out to GitHub. I started that process, should be in shortly.

Thanks for waiting - I'm glad to hear that Lyft is using this!

**Comment by SirVer** [comment]
@alexeagle Thank you very much!

**Pull request closed without merging**
